export interface IErrorMessageProvider {
  AUTH_INVALID_CREDENTIALS: string;
  AUTH_USER_NOT_FOUND: string;
  AUTH_EMAIL_NOT_CONFIRMED: string;
  AUTH_SESSION_EXPIRED: string;
  AUTH_UNAUTHORIZED: string;
  VALIDATION_REQUIRED: string;
  VALIDATION_INVALID_EMAIL: string;
  VALIDATION_INVALID_PHONE: string;
  VALIDATION_PASSWORD_TOO_WEAK: string;
  VALIDATION_PASSWORDS_NOT_MATCH: string;
  PAYMENT_FAILED: string;
  PAYMENT_INVALID_AMOUNT: string;
  PAYMENT_METHOD_NOT_SUPPORTED: string;
  INTERNAL_ERROR: string;
  NETWORK_ERROR: string;
  NOT_FOUND: string;
  RATE_LIMIT_EXCEEDED: string;
}
